import type { RouteConfig } from './types';

export function generateRoutesFile(routes: RouteConfig[]): string {
  if (routes.length === 0) {
    return `// Auto-generated by olova-router - DO NOT EDIT
import type { ComponentType } from 'react';

export interface Route {
  path: string;
  component: ComponentType;
}

export const routes: Route[] = [];

export type RoutePaths = never;
`;
  }

  const imports = routes
    .map((route, index) => `import Route${index} from '${route.component}';`)
    .join('\n');

  const routeObjects = routes
    .map((route, index) => {
      return `  { path: '${route.path}', component: Route${index} }`;
    })
    .join(',\n');

  const routePaths = routes.map(r => `'${r.path}'`).join(' | ');

  return `// Auto-generated by olova-router - DO NOT EDIT
import type { ComponentType } from 'react';

${imports}

export interface Route {
  path: string;
  component: ComponentType;
}

export const routes: Route[] = [
${routeObjects}
];

export type RoutePaths = ${routePaths};
`;
}
